Fix concurrent access crash in _all_opt_infos()
This patch avoids the following error raised when configuration
options are modified (e.g. by registering or unregistering an opt)
during iteration in mutate_config_files() or related methods:

RuntimeError: dictionary changed size during iteration

The error was observed in Neutron after oslo.service was refactored
to use dynamic backends, slightly changing signal handling and restart timing.

We fix this by copying the values of the affected dicts before iterating,
ensuring the iteration is stable and thread-safe.

Closes-Bug: #2100001
Change-Id: Ic576f7031e07f5615cd1fbc157ddfbb89b61a130
(cherry picked from commit bbb9ab163b4d0a9cb556e741215ad082762e8dbf)
(cherry picked from commit 485b600b2c1d0db9e6b2b7f8b0ce2b0965d6ae3f)
(cherry picked from commit bb1dd3bfbde11a3265b7ec5b735adc3a06bd8cd4)